
server:
  port: 8123

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  name: bancopopular
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bancopopular
    username: springstudent
    password: springstudent
  main:
    banner-mode: off
  flyway:
    enabled: true
    locations: classpath:db/migration # Padrão onde os scripts de migração devem estar

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
